name: CI

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: git config --global url."https://x-access-token:${{ secrets.ALZ_MODULES_PAT }}@github.com/TysonTech-net/".insteadOf "https://github.com/TysonTech-net/"
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
